---
apiVersion: apps/v1
items:
  - metadata:
      creationTimestamp: null
      labels:
        some-label-key: random-70-character-objkey-cmfuzg9tltcwlwnoyxjhy3rlci1uyw1lcci1uyw1lc
      name: random-70-character-objkey-cmfuzg9tltcwlwnoyxjhy3rlci-some-s
      namespace: some-namespace
      ownerReferences:
        - apiVersion: v1
          blockOwnerDeletion: true
          controller: true
          kind: Service
          name: some-svc
          uid: ""
    spec:
      selector:
        matchLabels:
          some-label-key: random-70-character-objkey-cmfuzg9tltcwlwnoyxjhy3rlci1uyw1lcci1uyw1lc
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            some-label-key: random-70-character-objkey-cmfuzg9tltcwlwnoyxjhy3rlci1uyw1lcci1uyw1lc
        spec:
          containers:
            - image: some-deployment:some-commit-sha
              name: some-deployment
              resources: {}
    status: {}
  - metadata:
      creationTimestamp: null
      labels:
        some-label-key: "1"
      name: random-70-character-name-cmfuzg9tltcwlwnoyxjhy3rlci1uy-f8d9db6b
      namespace: some-namespace
      ownerReferences:
        - apiVersion: v1
          blockOwnerDeletion: true
          controller: true
          kind: Service
          name: some-svc
          uid: ""
    spec:
      selector:
        matchLabels:
          some-label-key: "1"
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            some-label-key: "1"
        spec:
          containers:
            - image: some-deployment:some-commit-sha
              name: some-deployment
              resources: {}
    status: {}
kind: DeploymentList
metadata: {}

